baseURL = "https://itsorphic.com/"
languageCode = "en-us"
title = "orphic"

theme = "hugo-ficurinia"

author = "orphic"
copyright = "orphic - [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)."

paginate = 5
summaryLength = 30

[params]
    description = "orphic's meta thoughts"
    author = "orphic"
    
    posts = "posts"
    logo = "/logo.svg"
    favicon = "/favicon.png"
    faviconIco = "/favicon.ico"
    appletouch = "/apple-touch-icon.png"
    svgicon = "/logo.svg"
    icon512 = "/android-chrome-512x512.png"

    imageInArticlePreview = true

    enableRelatedArticles = true
    relatedArticlesNum = 2
    forceRedirect = true

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        lineNumbersInTable = false
        tabWidth = 4
        style = "vim"
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 1

[menu]
    [[menu.main]]
        identifier = "Writeups"
        name = "Writeups"
        url = "/writeups"
        weight = 99
    [[menu.icons]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/itsorphic"
        weight = 10
    [[menu.icons]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/migcardoso/"
        weight = 20
    [[menu.icons]]
        identifier = "email"
        name = "Email"
        url = "mailto:orphicxbt@proton.me"
        weight = 40

